Repository fosslight/fosslight_prechecker, pull requests merged in 2021-07, with the labels that each got.

#10 Update README
  README.md
  docs/user-guide.md
Labels: documentation

#11 Update version in setup.py when release
  .bumpversion.cfg
  .github/workflows/publish-release.yml
  .reuse/dep5
  src/fosslight_reuse/_fosslight_reuse.py
Labels: chore

#12 Remove waring in publish-release.yml
  .github/workflows/publish-release.yml
Labels: chore

#13 Bug fix to checkout new version
  .github/workflows/publish-release.yml
Labels: bug fix
