Repository fosslight/fosslight_prechecker, pull requests merged in 2022-10, with the labels that each got.

#108 Add OSS pkg file list for Nuget
  src/fosslight_prechecker/_constant.py
Labels: chore

#109 Fix bug in lint and add error for Windows
  src/fosslight_prechecker/_precheck.py
Labels: bug fix

#110 Fix bug that doesn't work -v, -h option
  src/fosslight_prechecker/cli.py
Labels: bug

#111 Fix bug for not working options(-n, i)
  README.md
  requirements-dev.txt
  src/fosslight_prechecker/_add.py
  src/fosslight_prechecker/_constant.py
  src/fosslight_prechecker/_help.py
  src/fosslight_prechecker/_precheck.py
  src/fosslight_prechecker/cli.py
Labels: bug

#112 Print license text through notice parameter
  .github/workflows/publish-release.yml
  .github/workflows/pull-request.yml
  setup.py
  src/fosslight_prechecker/_help.py
  src/fosslight_prechecker/cli.py
  tox.ini
Labels: chore
