Repository fosslight/fosslight_prechecker, pull requests merged in 2022-06, with the labels that each got.

#56 Apply parsing and convert new yaml format
  src/fosslight_oss_pkg/_parsing_excel.py
  src/fosslight_reuse/_add.py
  src/fosslight_reuse/_fosslight_reuse.py
  tests/convert/oss-pkg-info.yaml
Labels: chore

#57 Apply changed parsing_yaml return value
  requirements.txt
  src/fosslight_oss_pkg/_parsing_excel.py
  src/fosslight_reuse/_add.py
  src/fosslight_reuse/_fosslight_reuse.py
  src/fosslight_reuse/_result.py
  tox.ini
Labels: chore

#58 Fix the bug that Excel cannot be created if there is only one row in Convert mode
  src/fosslight_oss_pkg/_parsing_excel.py
  src/fosslight_reuse/_fosslight_reuse.py
Labels: bug fix

#59 Load SRC Sheet in excel
  src/fosslight_oss_pkg/_parsing_excel.py
Labels: chore

#60 Remove duplicate files in w/o license or copyright list
  src/fosslight_oss_pkg/fosslight_oss_pkg.py
  src/fosslight_reuse/_add.py
  src/fosslight_reuse/_fosslight_reuse.py
  src/fosslight_reuse/_result.py
  src/fosslight_reuse/cli.py
Labels: chore

#61 Check compliant except for files for which Exclude is True
  src/fosslight_reuse/_constant.py
  src/fosslight_reuse/_fosslight_reuse.py
  src/fosslight_reuse/_result.py
Labels: chore

#62 Apply -o option in add mode
  src/fosslight_reuse/_add.py
  src/fosslight_reuse/cli.py
Labels: chore

#63 Exclude for open source package file in w/o list
  src/fosslight_reuse/_constant.py
  src/fosslight_reuse/_fosslight_reuse.py
  src/fosslight_reuse/_result.py
Labels: chore

#64 Add the i (--ignore) option to not create a log file.
  src/fosslight_oss_pkg/fosslight_oss_pkg.py
  src/fosslight_reuse/_add.py
  src/fosslight_reuse/_fosslight_reuse.py
  src/fosslight_reuse/_help.py
  src/fosslight_reuse/cli.py
Labels: enhancement

#65 Make the sheet to convert selectable. (-s sheet name option)
  src/fosslight_oss_pkg/_parsing_excel.py
  src/fosslight_oss_pkg/fosslight_oss_pkg.py
  src/fosslight_reuse/_help.py
  src/fosslight_reuse/cli.py
Labels: enhancement

#66 Modification for compliance with pep8
  src/fosslight_reuse/_fosslight_reuse.py
Labels: chore

#67 update the minimum version of fosslight_util
  requirements.txt
Labels: chore

#68 Exclude for sbom info yaml file in Lint mode
  src/fosslight_reuse/_add.py
  src/fosslight_reuse/_constant.py
  src/fosslight_reuse/_fosslight_reuse.py
Labels: chore

#71 Change path to analyze path to print in lint mode
  src/fosslight_reuse/_fosslight_reuse.py
Labels: chore

#73 Add generating html format file
  src/fosslight_reuse/_constant.py
  src/fosslight_reuse/_fosslight_reuse.py
  src/fosslight_reuse/_result.py
  src/fosslight_reuse/_result_html.py
Labels: enhancement

#74 Add execution error handling for html
  src/fosslight_reuse/_result_html.py
Labels: chore

#75 Add expand button in html
  src/fosslight_reuse/_constant.py
  src/fosslight_reuse/_result_html.py
Labels: chore
