Repository fosslight/fosslight_prechecker, pull requests merged in 2022-11, with the labels that each got.

#113 Exclude untracked files and ignored files in lint mode
  src/fosslight_prechecker/_help.py
  src/fosslight_prechecker/_precheck.py
  src/fosslight_prechecker/_result.py
Labels: enhancement

#114 Exclude untracked files in input path
  src/fosslight_prechecker/_precheck.py
  src/fosslight_prechecker/_result.py
Labels: chore

#115 Modify downloading the license text
  src/fosslight_prechecker/_add.py
  src/fosslight_prechecker/_precheck.py
  src/fosslight_prechecker/cli.py
  src/fosslight_prechecker/resources/convert_license.json
Labels: chore

#116 Add tox configuration for Windows
  .github/workflows/pull-request.yml
  src/fosslight_oss_pkg/_parsing_excel.py
  src/fosslight_prechecker/_precheck.py
  src/fosslight_prechecker/cli.py
  src/fosslight_prechecker/resources/convert_license.json
  tox.ini
Labels: chore

#117 Modify to run all mode on Windows
  .github/workflows/publish-release.yml
  .github/workflows/pull-request.yml
  cli.py
  src/fosslight_prechecker/_precheck.py
Labels: enhancement

#118 Fix Dep5 encoding error
  src/fosslight_prechecker/_precheck.py
Labels: bug fix

#119 Replace windows operator to '/' for path in yaml
  src/fosslight_prechecker/_result.py
Labels: bug fix

#120 Fix yaml file encoding error
  src/fosslight_prechecker/_result.py
Labels: bug fix
